### ISSUE TITLE
Name of control characters U+0001 START OF HEADING and U+0002 START OF TEXT

### ISSUE THREAD

**Issue by aaaxx** [adobe-type-tools/agl-aglfn#3]
Out of all the ASCII control characters, these two have names that don't match the standard abbreviations (as given by [Unicode name aliases list](https://www.unicode.org/Public/10.0.0/ucd/NameAliases.txt) and every ASCII table out there). To make matters worse, U+0001 uses the standard abbreviation for U+0002.

Was this intentional or an error?

codepoint | Unicode                | Adobe
----------|------------------------|-----------
0001      | START OF HEADING (SOH) | control<b>STX</b>
0002      | START OF TEXT (<b>STX</b>)    | controlSOT

**Comment by kenlunde** [comment]
For better or worse, an extraordinarily large number of legacy fonts were produced using these apparently misnamed glyph names. Keep in mind that one purpose of AGL (aka _glyphlist.txt_) is to acknowledge such glyph names so that content can be properly derived and preserved. New fonts, on the other hand, are to adhere to AGLFN (aka _aglfn.txt_) and the [AGL Specification](https://github.com/adobe-type-tools/agl-specification), which results in _uni0001_ and _uni0002_ being used as the names for these particular glyphs.

**Comment by aaaxx** [comment]
OK, just to make sure I understand this:

When making new fonts, any glyphs that are not listed in `aglfn.txt` should be named `uni####` (or `u####` if outside of BMP), right?

And one more thing, which I don't think is completely clear in the spec, are suffixes meant only for _variants_ of the base glyph, or can I use them even on the base glyph itself, to make the hex names less opaque, for example (as in `uni0001.controlSOH`)?

**Comment by kenlunde** [comment]
To answer your first question: Yes.

And to answer your second question: Yes. Anything that follows the _full stop_ is dropped when interpreting the glyph name, so you are free to use glyph names such as _uni0001.controlSOH_.
