### ISSUE TITLE
dotlessj

### ISSUE THREAD

**Issue by jansindl3r** [adobe-type-tools/agl-aglfn#7]
is it possible that **dotlessj** in **glyphlist.txt** has unicode **F6BE** which is **PUA**, though it should have **567** in base **10**? Sorry if I am missing something out.

```
>>> chr(567)
'ȷ'
```

**Comment by puria** [comment]
Wow, seems it should be:

```
>>> import unicodedata
>>> ord(unicodedata.lookup('LATIN SMALL LETTER DOTLESS J'))
567
>>> hex(567)[2:].upper().zfill(4)
'0237'
```

**Comment by josh-hadley** [comment]
I'm not sure how you're using glyphlist.txt but it is important to understand its history and intended use: https://github.com/adobe-type-tools/agl-specification. In short:
> this specification is intended to be stable, meaning that it is never to be revised in a substantive way. In particular, it is intended that no mappings will ever be added to AGL

For new font development and glyph naming, most likely you will want to use the [*AGLFN*](https://github.com/adobe-type-tools/agl-aglfn/blob/master/aglfn.txt) rather than glyphlist.txt.
